### ISSUE TITLE
Avax seems not work at all

### ISSUE THREAD

**Issue by poudenes** [TheHolyRoger/hass-cryptoinfo#10]
Hi All,

Try to let this work. What I try its still not work:

```
- platform: cryptoinfo_advanced
  id: "AVAX USD"
  unique_id: "195faa94-8ca2-4d02-90f9-8df4baaf08a4"
  cryptocurrency_name: "avalanche"
  currency_name: "usd"
  unit_of_measurement: "$"
  multiplier: 1
  update_frequency: 5
  extra_sensors:
    - property: "24h_volume"
      unit_of_measurement: "$"
```

Can someone assist me with this one? BTC, XRP, SOL and ETH are working perfect
